[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "smart-home-observer"
version = "0.1.0"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "paho-mqtt",
    "python-dotenv",
    "pytest"
]

[project.scripts]
smart-home-observer = "smart_home_observer.__main__:run"

[tool.setuptools.packages.find]
where = ["src"]
