from typing import Protocol
from uuid import UUID

from topicgate.core.config.mqtt_config import MqttConfig
from topicgate.core.models.broker_profile import BrokerProfile


class BrokerProfileStore(Protocol):
    """Store broker profiles and their observer workspaces."""

    def get_profile(self, profile_id: UUID | None = None, /) -> BrokerProfile: ...

    def get_all_profiles(self) -> tuple[BrokerProfile, ...]: ...

    def create_profile(self, name: str, mqtt: MqttConfig, /) -> BrokerProfile: ...

    def update_profile(self, profile: BrokerProfile, /) -> None: ...

    def delete_profile(self, profile_id: UUID, /) -> BrokerProfile: ...

    def select_active_profile(self, profile_id: UUID, /) -> None: ...

    def replace_subscriptions(self, workspace_id: UUID, subscriptions, /) -> None: ...
